#!/usr/bin/env ruby
# List files *and* directories using ag
require 'set'
dirs = Set.new
IO.foreach('|ag -g ""') do |line|
  dir = File.dirname(line)
  anc = []
  while dir != '.' && dirs.add?(dir)
    anc << dir
    dir = File.dirname(dir)
  end
  puts anc.reverse unless anc.empty?
  print line
end
